baseurl = "https://lixiucheng.com"
title = "I'm Xiuc"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

timeout = 300000

# We don't want to canonify URLs because it prevents us from
# deploying drafts of the site to alternate hosts.
canonifyurls = false

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

buildFuture = true
hasCJKLanguage = true

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    style = "native"
  [markup.goldmark.renderer]
    # Allow Markdown to include embedded HTML.
    unsafe= true

[permalinks]
    posts = "/:contentbasename/"

[params]
    dateFormat = "January 2, 2006"
    author = "Xiuc"
    avatarurl = "images/avatar.jpg"
    since = "2024"
    footercontent = "power by <a href=\"https://github.com/x1uc/lixiucheng.com\" target=\"_blank\">lixiucheng.com</a>"

    favicon_32 = "/images/favicon/favicon-32x32.jpg"
    favicon_16 = "/images/favicon/favicon-16x16.jpg"

    hidecredits = false
    hidecopyright = false
    popularPosts = []
    rtl = false
    photoWidths = [300, 600, 800, 1200]

[imaging]
quality = 90
resampleFilter = "Lanczos"

# Social links

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "翻译"
    weight = 2
    url = "/translations/"
[[menu.main]]
    name = "月度回顾"
    weight = 3
    url = "/retrospectives/"
[[menu.main]]
    name = "关于"
    weight = 4
    url = "/about/"
